name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    uses: gh-top-languages/.github/.github/workflows/test.yml@v1.0.0

  build:
    uses: gh-top-languages/.github/.github/workflows/build.yml@v1.0.0
