name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    uses: gh-top-languages/.github/.github/workflows/test.yml@v1.0.0

  publish:
    needs: test
    permissions:
      contents: write
    uses: gh-top-languages/.github/.github/workflows/publish.yml@v1.0.0
    secrets: inherit
